#!/usr/bin/perl

use strict;


my $INFILE = 'landtag-tirol.csv';

open ( IN, "< $INFILE") || die("cannot open $INFILE: $! \n");

my @sprachliste = ("mul","en","bar","br","ca","co","da","de","de-at","es","fr","id","it","nds","nl","nb","pl","pt","pt-br","ro","sl","sv","ty","ast");

my $count =0 ;
while(<IN>)
{
    chop;

    my ($name,$partei,$geschlecht) = split(/\,/,$_);
#    my ($name,$partei,$geschlecht) = split(/\t/,$_);
    # print "NAME:$name:$partei:GENDER:$geschlecht:\n";
    
    # $kat =~ s/^(\s)*//og; # trim
    # $kat =~ s/(\s)*$//og; # trim

    print "CREATE\n";
    foreach my $sprache (@sprachliste) {
      print "LAST\tL".$sprache."\t\"".$name."\"\n";
    }

    my $beschreibung = "";
    my $beschreibung_es = "";
    my $beschreibung_nl = "";
    if ($geschlecht eq "Frau") {
	$beschreibung = "österreichische Politikerin (".$partei.")";
	print "LAST\tP21\tQ6581072\n"; # geschlecht weiblich
	$beschreibung_es = "política austríaca";
	$beschreibung_nl = "politica uit Oostenrijk";
    }
    if ($geschlecht eq "Mann") {
	$beschreibung = "österreichischer Politiker (".$partei.")";
	print "LAST\tP21\tQ6581097\n"; # geschlecht maennlich
	$beschreibung_es = "político austríaco";
	$beschreibung_nl = "politicus uit Oostenrijk";
    }
    
    if ($partei eq "GRÜNE") {
	print "LAST\tP102\tQ193178\n"; # parteizugehörigkeit grüne
	print "LAST\tP102\tQ15805742\n"; # grüne tirol
    }

    if ($partei eq "ÖVP") {
	print "LAST\tP102\tQ186867\n"; # parteizugehörigkeit
	print "LAST\tP102\tQ2436307\n"; # tirol
    }

    if ($partei eq "SPÖ") {
	print "LAST\tP102\tQ179111\n"; # parteizugehörigkeit
	print "LAST\tP102\tQ2207623\n"; # 
    }

    if ($partei eq "FPÖ") {
	print "LAST\tP102\tQ131692\n"; # parteizugehörigkeit
    }

    if ($partei eq "NEOS") {
	print "LAST\tP102\tQ13564543\n"; # parteizugehörigkeit
    }

    print "LAST\tDde\t\"".$beschreibung."\"\n";
    print "LAST\tDen\t\"Austrian politician\"\n";
    print "LAST\tDes\t\"".$beschreibung_es."\"\n";
    print "LAST\tDnl\t\"".$beschreibung_nl."\"\n";
    
    
    print "LAST\tP31\tQ5\n"; # mensch
    print "LAST\tP106\tQ82955\n"; # politiker
    print "LAST\tP27\tQ40\n"; # österreicher
    print "LAST\tP1412\tQ188\n"; # deutsch

    # +1967-01-17T00:00:00Z/11
    print "LAST\tP39\tQ88748902\tP580\t+2022-10-25T00:00:00Z/11\n";  # Mitglied des Tiroler Landtages (Q88748902) ab 25.10.2022
   

}
close(IN);
