#!/usr/bin/perl

use strict;

# CREATE		
# LAST	P31	Q4167836
# LAST	Sdewiki	Kategorie:Geographie (Bezirk Bruck-Mürzzuschlag)
# LAST	Lde	Kategorie:Geographie (Bezirk Bruck-Mürzzuschlag)

my $INFILE = 'list.txt';

open ( IN, "< $INFILE") || die("cannot open $INFILE: $! \n");

my $count =0 ;
while(<IN>)
{
    chop;
    my ($ND_ID, $ND_NAME) = split(/\t/,$_);
    $ND_NAME =~ s/^(\s)*//og; # trim
    $ND_NAME =~ s/(\s)*$//og; # trim
    $ND_NAME =~ s/_/ /og; # trim
    
    
    print "CREATE\n";
    print "LAST\tLde\t\"$ND_NAME\"\n"; # label de - bezeichnung
     print "LAST\tAde\t\"$ND_ID\"\n"; #   
       print "LAST\tP31\tQ21573182\n"; # ist ein Naturdenkmal in Deutschland (Q21573182)
    print "LAST\tP17\tQ183\n"; # Staat: Deutschland
#    print "LAST\tP131\tQ505158\n"; # liegt in der Verwaltungseinheit: Tittmoning (Q505158)
#    print "LAST\tP131\tQ574661\n"; # liegt in der Verwaltungseinheit: Tacherting (Q574661)
#    print "LAST\tP131\tQ253804\n"; # liegt in der Verwaltungseinheit: Taching am See (Q253804)
    print "LAST\tP131\tQ253119\n"; # liegt in der Verwaltungseinheit: Traunstein (Q253119)


#     print "LAST\tDde\t\"Naturdenkmal in Tittmoning\"\n"; #   
#     print "LAST\tDde\t\"Naturdenkmal in Tacherting\"\n"; #   
#     print "LAST\tDde\t\"Naturdenkmal in Taching am See\"\n"; #   
     print "LAST\tDde\t\"Naturdenkmal in Traunstein\"\n"; #   



	#    print "LAST\tAde\t\"$alias1\"\n"; # alias de - alias
    #  print "LAST\tAde\t\"$alias2\"\n"; # alias de - alias
     # if ($lemma_ohne_klammerzusatz ne $lemma_mit_klammerzusatz) {
#	print "LAST\tAde\t\"$lemma_mit_klammerzusatz\"\n"; # alias de - alias
#     } else {
	 


}
close(IN);
