#!/usr/bin/perl

use strict;

# CREATE		
# LAST	P31	Q4167836
# LAST	Sdewiki	Kategorie:Geographie (Bezirk Bruck-Mürzzuschlag)
# LAST	Lde	Kategorie:Geographie (Bezirk Bruck-Mürzzuschlag)

my $INFILE = 'list.txt';

open ( IN, "< $INFILE") || die("cannot open $INFILE: $! \n");



 my $count =0 ;

  my $count =11 ;


while(<IN>)
{
    chop;
    my $kat = $_;
    $kat =~ s/^(\s)*//og; # trim
    $kat =~ s/(\s)*$//og; # trim
    $kat =~ s/_/ /og; # trim
    
    # print "KAT:$kat:\n";

$count++;
 
if ($kat eq "Birinci Lig 2006/07") { $count++; }
 
    print "CREATE\n";
    print "LAST\tLde\t\"$kat\"\n"; # label de - bezeichnung
    print "LAST\tP31\tQ27020041\n"; # ist eine: Spielsaison

# my $beschreibung = $count.". Austragung der Schweizer Rugby-Union-Meisterschaft";

# my $beschreibung = $count.". Saison der höchsten zyperntürkischen Spielklasse im Männerfußball";
 my $beschreibung = "Saison der höchsten zyperntürkischen Spielklasse im Männerfußball";


 print "LAST\tDde\t\"".$beschreibung."\"\n"; # label de - 
 

#    print "LAST\tP17\tQ183\n"; # Staat: Deutschland
#     print "LAST\tP17\tQ16957\n"; # Staat: DDR
    # print "LAST\tP17\tQ39\n"; # Staat: Schweiz
     print "LAST\tP17\tQ229\n"; # Staat: Zypern
	
	
     print "LAST\tP641\tQ2736\n"; # Sportart: Fußball
    # print "LAST\tP641\tQ5849\n"; # Sportart: Rugby Union
    
	 print "LAST\tP3450\tQ2180367\n"; # Liga: Kuzey Kıbrıs Süper Ligi / Birinci Lig

		
    # print "LAST\tP3450\tQ109935010\n"; # Liga: Fußball-Bezirksliga Rostock
# print "LAST\tP3450\tQ2952014\n"; #     Fußball-Bezirksliga Gera (Q2952014)
# print "LAST\tP3450\tQ2952014\n"; #     Fußball-Bezirksliga Gera (Q2952014)
# print "LAST\tP3450\tQ2952228\n"; #     Schweizer Rugby-Union-Meisterschaft (Q2952228)
 #print "LAST\tP3450\tQ27909673\n"; # Fußball-Bezirksliga Berlin (Q27909673)
# print "LAST\tP3450\tQ324698\n"; # Liga: Mittelrheinliga

# print "LAST\tP664\tQ3741046\n"; #     # Veranstalter (P664): Fédération Suisse de Rugby (Q3741046)

    


}
close(IN);
