#!/usr/bin/perl

use strict;

# Crypt::SSLeay muss installiert sein fuer SSL-Support
# apt-get install libwww-mechanize-perl libio-socket-ssl-perl libnet-ssleay-perl
use WWW::Mechanize;
use Data::Dumper;
use HTML::FormatText;
my $USER_AGENT='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36';
# See the autocheck parameter, which turns all HTTP errors into fatal errors. When you turn autocheck off, you will need to do all error checking yourself.
my $agent = WWW::Mechanize->new( agent => $USER_AGENT,  autocheck => 0 );

#http://glennf.com/writing/hexadecimal.url.encoding.html
# This pattern takes the hex characters and decodes them back into real characters. The function hex() turns a hex number into decimal; 
# there is no dec() that does the reverse in perl. The "e" at the end of the regexp means "evaluate the replacement pattern as an expression."
sub URLDecode {
    my $theURL = $_[0];
    $theURL =~ tr/+/ /;
    $theURL =~ s/%([a-fA-F0-9]{2,2})/chr(hex($1))/eg;
    $theURL =~ s/<!--(.|\n)*-->//g;
    return $theURL;
}

sub URLEncode {
    my $theURL = $_[0];
    $theURL =~ s/([\W])/"%" . uc(sprintf("%2.2x",ord($1)))/eg;
    return $theURL;
}



# Cultural heritage monuments in Hesse with known ID

# https://petscan.wmflabs.org/?search_filter=&edits%5Bflagged%5D=both&language=commons&interface_language=en&edits%5Banons%5D=both&cb_labels_no_l=1&ns%5B14%5D=1&since_rev0=&show_redirects=no&search_max_results=500&cb_labels_yes_l=1&wikidata_item=without&edits%5Bbots%5D=both&categories=Cultural%20heritage%20monuments%20in%20Hesse%20with%20known%20ID&project=wikimedia&cb_labels_any_l=1&&doit=


# Weilburg
# https://petscan.wmflabs.org/?templates_no=&edits%5Bbots%5D=both&cb_labels_any_l=1&ns%5B14%5D=1&language=commons&search_max_results=500&edits%5Banons%5D=both&cb_labels_no_l=1&cb_labels_yes_l=1&since_rev0=&edits%5Bflagged%5D=both&wikidata_item=without&show_redirects=no&interface_language=en&categories=Cultural%20heritage%20monuments%20in%20Hesse%20with%20known%20ID%0ACultural%20heritage%20monuments%20in%20Seligenstadt&project=wikimedia&sparql=&doit=


#
# - baudenkmaler in Sachsen/Meißen + id
#
# Cultural heritage monuments in Hesse without linked Wikidata
# Dresden
# 
# https://petscan.wmflabs.org/?&search_max_results=500&cb_labels_yes_l=1&language=commons&edits%5Bbots%5D=both&edits%5Bflagged%5D=both&interface_language=en&edits%5Banons%5D=both&wikidata_item=without&project=wikimedia&depth=10&show_redirects=no&cb_labels_no_l=1&ns%5B14%5D=1&categories=Cultural%20heritage%20monuments%20in%20Saxony%20without%20linked%20Wikidata%0ADresden%0A&cb_labels_any_l=1&&doit=

###################
# https://commons.wikimedia.org/wiki/Category:Cultural_heritage_monuments_in_Hofgeismar
# https://petscan.wmflabs.org/?&cb_labels_any_l=1&categories=Cultural%20heritage%20monuments%20in%20Hofgeismar&wikidata_item=without&interface_language=en&since_rev0=&cb_labels_yes_l=1&language=commons&depth=10&cb_labels_no_l=1&show_redirects=no&edits%5Bflagged%5D=both&project=wikimedia&edits%5Bbots%5D=both&ns%5B14%5D=1&search_max_results=500&edits%5Banons%5D=both&doit=


# https://petscan.wmflabs.org/?&cb_labels_any_l=1&categories=Cultural%20heritage%20monuments%20in%20Kronberg%20im%20Taunus&wikidata_item=without&interface_language=en&since_rev0=&cb_labels_yes_l=1&language=commons&depth=10&cb_labels_no_l=1&show_redirects=no&edits%5Bflagged%5D=both&project=wikimedia&edits%5Bbots%5D=both&ns%5B14%5D=1&search_max_results=500&edits%5Banons%5D=both&doit=


# https://commons.wikimedia.org/wiki/Category:Churches_in_Hesse

# https://petscan.wmflabs.org/?&cb_labels_any_l=1&categories=Churches_in_Hesse&wikidata_item=without&interface_language=en&since_rev0=&cb_labels_yes_l=1&language=commons&depth=10&cb_labels_no_l=1&show_redirects=no&edits%5Bflagged%5D=both&project=wikimedia&edits%5Bbots%5D=both&ns%5B14%5D=1&search_max_results=500&edits%5Banons%5D=both&doit=

###################

# SELECT ?item ?itemLabel ?value ?liegt_in_der_Verwaltungseinheit ?liegt_in_der_VerwaltungseinheitLabel ?Bild WHERE {
#  ?item wdt:P1708 ?value.
#  ?item wdt:P131 wdt:Q8738.
#  SERVICE wikibase:label { bd:serviceParam wikibase:language "de,en". }
#  OPTIONAL { ?item wdt:P131 ?liegt_in_der_Verwaltungseinheit. }
#  OPTIONAL { ?item wdt:P18 ?Bild. }
# } order by ?liegt_in_der_VerwaltungseinheitLabel



my $INFILE = 'list.txt';

open ( IN, "< $INFILE") || die("cannot open $INFILE: $! \n");

my $count =0 ;
while(<IN>)
{
    chop;
    my $kat = $_;
    $kat =~ s/^(\s)*//og; # trim
    $kat =~ s/(\s)*$//og; # trim
    $kat =~ s/_/ /og; # trim
    
    # print "KAT:$kat:\n";
         if ($kat eq "") { next ; }
    my $lemma_mit_klammerzusatz = $kat;  # ohne präfix "category:"
    $lemma_mit_klammerzusatz =~ s/Category://iog;
    #fixme

    my $lemma_ohne_klammerzusatz = $lemma_mit_klammerzusatz;  # ohne präfix und klammerzusatz
    $lemma_ohne_klammerzusatz =~ s/\(.+\)//og;
    $lemma_ohne_klammerzusatz =~ s/^(\s)*//og; # trim
    $lemma_ohne_klammerzusatz =~ s/(\s)*$//og; # trim

    my $lemma_ohne_klammer_aber_mit_zusatz = $lemma_mit_klammerzusatz;  # ohne präfix 
    $lemma_ohne_klammer_aber_mit_zusatz =~ s/^(\s)*//og; # trim
    $lemma_ohne_klammer_aber_mit_zusatz =~ s/(\s)*$//og; # trim
    $lemma_ohne_klammer_aber_mit_zusatz =~ s/\(//og;
    $lemma_ohne_klammer_aber_mit_zusatz =~ s/\)//og;
    
    my $kat_mit_prefix = "Category:".$kat;

   
        
    my $klammerzusatz = "";
    if ($lemma_mit_klammerzusatz =~ /\((.+)\)/og) {
      $klammerzusatz = $1;
      # print "KLAMMERZUSATZ:$klammerzusatz:\n";
    }
    
   
   ##############

   #   my $url = 'https://commons.wikimedia.org/wiki/Category:Dorfkirche_(Herzsprung_in_der_Uckermark)';
     my $url = 'https://commons.wikimedia.org/wiki/Category:'.URLEncode($kat);
    
#      my $lemma = "";
#     my $lemma_decode = "";
#     if ($url =~ /Category:(.*)$/) {
#        $lemma = $1;
#        $lemma_decode = URLDecode($lemma);
#        $lemma_decode =~ s/_/ /og;
#      }
#       print "LEMMA:$lemma:DECODE:$lemma_decode:\n";
     
       my $check_url = $url.'?action=raw';
       # print "check URL:$check_url:\n"; # exit;

    $agent->get( $check_url );
  my $result2 = $agent->content;
  # print "RESULT:$result2:\n";
  
#       if ($result2 =~ /Wikidata infobox/i) {
#        print STDERR "Lemma $check_url hat Wikidata Infobox - do nothing\n";
#        next;
#     } 

#  {{Kulturdenkmal Hessen|99901}}
  my $blfd_id = "";
  if ($result2 =~ /Kulturdenkmal Hessen/i) {
     # print "Lemma $check_url hat Baudenkmal-ID\n";
 
       if ($result2 =~ /(\s*)\{\{Kulturdenkmal Hessen(\s*)\|(1=)?(\s*)([0-9]+)/i) {
         # print "*** HIER: $1:$2:$3:$4:\n";
#           $blfd_id = $4;
           $blfd_id = $5;
     }
    #     print "Lemma $check_url hat Baudenkmal-ID $blfd_id:\n";
   } # Baudenkmal

my $north = "";
my $east = "";

# {{Object location dec|50.18018|8.50611|region:DE}}


  if ($result2 =~ /Object location/i) {
      # print "Lemma $check_url hat Object location\n";
      if ($result2 =~ /(\s*)\{\{Object location( dec)?(\s*)\|(\s*)([0-9\.]+)(\s*)\|(\s*)([0-9\.]+)(\s*)/i) {
        # print "*** HIER: 1:$1:2.$2:3:$3:4:$4:5:$5:6:$6:7:$7:8:$8\n";
$north = $5;
$east = $8;
     }
        # print "Lemma $check_url hat location $north $east:\n";
   } # Baudenkmal
   
##############


   
   
    # print "KAT:$kat:LEMMA_MIT:$lemma_mit_klammerzusatz:LEMMA_OHNE:$lemma_ohne_klammerzusatz:\n";
    
    print "CREATE\n";
   print "LAST\tLde\t\"$lemma_ohne_klammerzusatz\"\n"; # label de - bezeichnung


    my $alias = $lemma_mit_klammerzusatz;
    if ($lemma_mit_klammerzusatz ne $lemma_ohne_klammerzusatz) {
      print "LAST\tAde\t\"$alias\"\n"; # alias de - alias
    }
  
# my $beschreibung = "Bauwerk in Kronberg im Taunus, Hochtaunuskreis, Hessen";
# my $beschreibung = "Bauwerk in Kiedrich, Rheingau-Taunus-Kreis, Hessen";

#my $beschreibung = "Wasserturm in Hessen";
#my $beschreibung = "Wasserturm";

# my $beschreibung = "Bauwerk in Hofgeismar, Landkreis Kassel, Hessen";
 my $beschreibung = "Kirchengebäude";
# my $beschreibung = "Bauwerk in Königstein im Taunus, Hochtaunuskreis, Hessen";


# my $beschreibung = "Bauwerk in Seligenstadt, Landkreis Offenbach, Hessen";

# my $beschreibung = "Bauwerk";  
if ($klammerzusatz ne "") { $beschreibung = $beschreibung." in ".$klammerzusatz; }
        print "LAST\tDde\t\"$beschreibung\"\n"; # description de - beschreibung
    
    print "LAST\tScommonswiki\t\"$kat_mit_prefix\"\n"; # sitelink
     print "LAST\tP31\tQ16970\n"; # ist eine: Kirchengebäude
#    P31:Q41176 # gebäude

# print "LAST\tP31\tQ811979\n"; # ist eine: Bauwerk
#print "LAST\tP31\tQ41176\n"; # ist eine: Gebäude
#print "LAST\tP31\tQ274153\n"; # ist eine: Wasserturm

    print "LAST\tP17\tQ183\n"; # Staat: Deutschland

            print "LAST\tP131\tQ1199\n"; # liegt in der Verwaltungseinheit: Hessen (Q1199)
#            print "LAST\tP131\tQ569661\n"; # liegt in der Verwaltungseinheit: Königstein im Taunus
#            print "LAST\tP131\tQ516529\n"; # liegt in der Verwaltungseinheit: Seligenstadt (Q516529)
            
#            print "LAST\tP131\tQ569634\n"; # liegt in der Verwaltungseinheit:             Kronberg im Taunus (Q569634)
#            print "LAST\tP131\tQ382481\n"; # liegt in der Verwaltungseinheit:             Büdingen (Q382481)
#            print "LAST\tP131\tQ627351\n"; # liegt in der Verwaltungseinheit:                         Kiedrich (Q627351)
 #       print "LAST\tP131\tQ490449\n"; # liegt in der Verwaltungseinheit: Hofgeismar (Q490449)
#            print "LAST\tP131\tQ573599\n"; # liegt in der Verwaltungseinheit: Weilburg (Q573599)

# print "LAST\tP131\tQ3042\n"; # liegt in der Verwaltungseinheit: Offenbach am Main (Q3042)
#                        print "LAST\tP131\tQ7044\n"; # liegt in der Verwaltungseinheit: Oberursel (Q7044)
#                        print "LAST\tP131\tQ16105\n"; # liegt in der Verwaltungseinheit: Bad Nauheim (Q16105)
#                        print "LAST\tP131\tQ4165\n"; # liegt in der Verwaltungseinheit: Bad Homburg vor der Höhe (Q4165)
#                        print "LAST\tP131\tQ1794\n"; # liegt in der Verwaltungseinheit: Frankfurt am Main (Q1794)
#                        print "LAST\tP131\tQ16082\n"; # liegt in der Verwaltungseinheit: Bad Vilbel (Q16082)
#                        print "LAST\tP131\tQ570892\n"; # liegt in der Verwaltungseinheit: Münzenberg (Q570892)
#                        print "LAST\tP131\tQ14872\n"; # liegt in der Verwaltungseinheit: Bensheim (Q14872)
#                        print "LAST\tP131\tQ633608\n"; # liegt in der Verwaltungseinheit: Ober-Mörlen (Q633608)
#                        print "LAST\tP131\tQ617180\n"; # liegt in der Verwaltungseinheit: Rockenberg (Q617180)


             
 
    print "LAST\tP373\t\"$kat\"\n";   # Commonscat-Property
   
   if ($blfd_id ne "") {
      print "LAST\tP1769\t\"$blfd_id\"\n";   # LSFID
	  
	         print "LAST\tP1435\tQ85171284\n"; # kulturdenkmal in hessen

 # tellt: Schutzkategorie (P1435): Kulturdenkmal in Hessen (Q85171284)
 
  }
  
  
    
    if (($north ne "") && ($east ne "")) {
  my $cord = '@'.$north.'/'.$east;
    print "LAST\tP625\t$cord\n";   # koordinaten 
 }
 

}
close(IN);
