#!/usr/bin/perl

use strict;

# Crypt::SSLeay muss installiert sein fuer SSL-Support
# apt-get install libwww-mechanize-perl libio-socket-ssl-perl libnet-ssleay-perl
use WWW::Mechanize;
use Data::Dumper;
use HTML::FormatText;
my $USER_AGENT='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36';
# See the autocheck parameter, which turns all HTTP errors into fatal errors. When you turn autocheck off, you will need to do all error checking yourself.
my $agent = WWW::Mechanize->new( agent => $USER_AGENT,  autocheck => 0 );

#http://glennf.com/writing/hexadecimal.url.encoding.html
# This pattern takes the hex characters and decodes them back into real characters. The function hex() turns a hex number into decimal; 
# there is no dec() that does the reverse in perl. The "e" at the end of the regexp means "evaluate the replacement pattern as an expression."
sub URLDecode {
    my $theURL = $_[0];
    $theURL =~ tr/+/ /;
    $theURL =~ s/%([a-fA-F0-9]{2,2})/chr(hex($1))/eg;
    $theURL =~ s/<!--(.|\n)*-->//g;
    return $theURL;
}

sub URLEncode {
    my $theURL = $_[0];
    $theURL =~ s/([\W])/"%" . uc(sprintf("%2.2x",ord($1)))/eg;
    return $theURL;
}


# https://commons.wikimedia.org/wiki/Category:Streets_in_Biel/Bienne

# https://petscan.wmflabs.org/?before=&active_tab=tab_categories&min_sitelink_count=&max_age=&project=wikimedia&search_filter=&ns%5B4%5D=1&sparql=&maxlinks=&ns%5B14%5D=1&ores_prob_from=&langs_labels_no=&ns%5B0%5D=1&cb_labels_any_l=1&language=commons&pagepile=&cb_labels_yes_l=1&wpiu=any&manual_list_wiki=&source_combination=&show_soft_redirects=both&wikidata_item=without&cb_labels_no_l=1&show_redirects=no&search_max_results=500&page_image=any&sitelinks_yes=&categories=Streets+in+Biel%2FBienne&sitelinks_any=&sortorder=ascending&ores_prediction=any&labels_no=&negcats=Wikipedia%3AL%C3%B6schkandidat%0D%0AWikipedia%3ASchnelll%C3%B6schen&edits%5Banons%5D=both&minlinks=&search_wiki=&wikidata_prop_item_use=&show_disambiguation_pages=both&interface_language=en&langs_labels_any=&ores_type=any&combination=union&search_query=&smaller=&doit=




my $INFILE = 'list.txt';

open ( IN, "< $INFILE") || die("cannot open $INFILE: $! \n");

my $count =0 ;
while(<IN>)
{
    chop;
    my $kat = $_;
    $kat =~ s/^(\s)*//og; # trim
    $kat =~ s/(\s)*$//og; # trim
    $kat =~ s/_/ /og; # trim
    
    # print "KAT:$kat:\n";
    
    my $lemma_mit_klammerzusatz = $kat;  # ohne präfix "category:"
    $lemma_mit_klammerzusatz =~ s/Category://iog;
    #fixme

    my $lemma_ohne_zusatz = $lemma_mit_klammerzusatz;  # ohne präfix und klammerzusatz
    $lemma_ohne_zusatz =~ s/\(.+//og;
    $lemma_ohne_zusatz =~ s/^(\s)*//og; # trim
    $lemma_ohne_zusatz =~ s/(\s)*$//og; # trim

    
    my $kat_mit_prefix = "Category:".$kat;

    
##############

   #   my $url = 'https://commons.wikimedia.org/wiki/Category:Dorfkirche_(Herzsprung_in_der_Uckermark)';
     my $url = 'https://commons.wikimedia.org/wiki/Category:'.URLEncode($kat);
    
#      my $lemma = "";
#     my $lemma_decode = "";
#     if ($url =~ /Category:(.*)$/) {
#        $lemma = $1;
#        $lemma_decode = URLDecode($lemma);
#        $lemma_decode =~ s/_/ /og;
#      }
#       print "LEMMA:$lemma:DECODE:$lemma_decode:\n";
     
       my $check_url = $url.'?action=raw';
       # print "check URL:$check_url:\n"; # exit;

    $agent->get( $check_url );
  my $result2 = $agent->content;
  # print "RESULT:$result2:\n";
  
       if ($result2 =~ /Wikidata infobox/i) {
        # print STDERR "Lemma $check_url hat Wikidata Infobox \n";
       # next;
     } 


my $north = "";
my $east = "";
  if ($result2 =~ /Object location/i) {
      # print "Lemma $check_url hat Object location\n";
      if ($result2 =~ /(\s*)\{\{Object location( dec)?(\s*)\|(\s*)([0-9\.]+)(\s*)\|(\s*)([0-9\.]+)(\s*)\}/i) {
       #  print "*** HIER: 1:$1:2.$2:3:$3:4:$4:5:$5:6:$6:7:$7:8:$8\n";
$north = $5;
$east = $8;
     }
        # print "Lemma $check_url hat location $north $east:\n";
   } # Baudenkmal
   
##############

    
    # print "KAT:$kat:LEMMA_MIT:$lemma_mit_klammerzusatz:LEMMA_OHNE:$lemma_ohne_klammerzusatz:\n";
    
    print "CREATE\n";
   print "LAST\tLde\t\"$lemma_ohne_zusatz\"\n"; # label de - bezeichnung
   print "LAST\tLen\t\"$lemma_ohne_zusatz\"\n"; # label de - bezeichnung

    my $alias = $lemma_ohne_zusatz;
      print "LAST\tAde\t\"".$alias.", Biel/Bienne\"\n"; # alias de - alias
      print "LAST\tAen\t\"".$alias.", Biel/Bienne\"\n"; # alias de - alias
      print "LAST\tAde\t\"".$alias." (Biel/Bienne)\"\n"; # alias de - alias
      print "LAST\tAen\t\"".$alias." (Biel/Bienne)\"\n"; # alias de - alias
  
     my $beschreibung = "Straße in Biel/Bienne";
     my $beschreibung_en = "street in Biel/Bienne";
	 
#     my $beschreibung = "Platz in Biel/Bienne";
#     my $beschreibung_en = "square in Biel/Bienne";
	 
     print "LAST\tDde\t\"$beschreibung\"\n"; # description de - beschreibung
     print "LAST\tDen\t\"$beschreibung_en\"\n"; # description en - beschreibung
    
    print "LAST\tScommonswiki\t\"$kat_mit_prefix\"\n"; # sitelink
	
	
    print "LAST\tP17\tQ39\n"; # Staat: Schweiz (Q39)
    print "LAST\tP131\tQ1034\n"; # liegt in der Verwaltungseinheit: Biel/Bienne (Q1034)


    print "LAST\tP373\t\"$kat\"\n";   # Commonscat-Property



    print "LAST\tP31\tQ79007\n"; # ist eine: Innerortsstraße
#  		   print "LAST\tP31\tQ174782\n"; # ist eine: Platz (Q174782)


    
    if (($north ne "") && ($east ne "")) {
  my $cord = '@'.$north.'/'.$east;
    print "LAST\tP625\t$cord\n";   # koordinaten 
 }
   


}
close(IN);
