#!/usr/bin/perl

use strict;

# Crypt::SSLeay muss installiert sein fuer SSL-Support
# apt-get install libwww-mechanize-perl libio-socket-ssl-perl libnet-ssleay-perl
use WWW::Mechanize;
use Data::Dumper;
use HTML::FormatText;
my $USER_AGENT='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36';
# See the autocheck parameter, which turns all HTTP errors into fatal errors. When you turn autocheck off, you will need to do all error checking yourself.
my $agent = WWW::Mechanize->new( agent => $USER_AGENT,  autocheck => 0 );

#http://glennf.com/writing/hexadecimal.url.encoding.html
# This pattern takes the hex characters and decodes them back into real characters. The function hex() turns a hex number into decimal; 
# there is no dec() that does the reverse in perl. The "e" at the end of the regexp means "evaluate the replacement pattern as an expression."
sub URLDecode {
    my $theURL = $_[0];
    $theURL =~ tr/+/ /;
    $theURL =~ s/%([a-fA-F0-9]{2,2})/chr(hex($1))/eg;
    $theURL =~ s/<!--(.|\n)*-->//g;
    return $theURL;
}

sub URLEncode {
    my $theURL = $_[0];
    $theURL =~ s/([\W])/"%" . uc(sprintf("%2.2x",ord($1)))/eg;
    return $theURL;
}

# - intersection 
# - depth 20
# negative:
# Nur kategorien, keine galerien !!!   
# 
# https://petscan.wmflabs.org/?links_to_no=&depth=20&language=commons&project=wikimedia&search_max_results=500&cb_labels_no_l=1&since_rev0=&edits%5Bbots%5D=both&show_redirects=no&negcats=Interiors%20of%20churches%20in%20Brandenburg&interface_language=en&ns%5B14%5D=1&wikidata_item=without&edits%5Banons%5D=both&cb_labels_yes_l=1&categories=Churches_in_Schleswig-Holstein&cb_labels_any_l=1&edits%5Bflagged%5D=both&doit=

# https://commons.wikimedia.org/wiki/Category:Churches_in_Schleswig-Holstein


# https://commons.wikimedia.org/wiki/Category:Dr.-Julius-Leber-Stra%C3%9Fe_(L%C3%BCbeck)
# https://commons.wikimedia.org/wiki/Category:Cultural_heritage_monuments_in_L%C3%BCbeck-Altstadt


my $INFILE = 'list.txt';

open ( IN, "< $INFILE") || die("cannot open $INFILE: $! \n");

my $count =0 ;
while(<IN>)
{
    chop;
    my $kat = $_;
    $kat =~ s/^(\s)*//og; # trim
    $kat =~ s/(\s)*$//og; # trim
    $kat =~ s/_/ /og; # trim
    
    # print "KAT:$kat:\n";

    if ($kat eq "") { next ; }
    
    
    my $lemma_mit_klammerzusatz = $kat;  # ohne präfix "category:"
    $lemma_mit_klammerzusatz =~ s/Category://iog;
    #fixme

    my $lemma_ohne_klammerzusatz = $lemma_mit_klammerzusatz;  # ohne präfix und klammerzusatz
    $lemma_ohne_klammerzusatz =~ s/\(.+\)//og;
    $lemma_ohne_klammerzusatz =~ s/^(\s)*//og; # trim
    $lemma_ohne_klammerzusatz =~ s/(\s)*$//og; # trim

    my $lemma_ohne_klammer_aber_mit_zusatz = $lemma_mit_klammerzusatz;  # ohne präfix 
    $lemma_ohne_klammer_aber_mit_zusatz =~ s/^(\s)*//og; # trim
    $lemma_ohne_klammer_aber_mit_zusatz =~ s/(\s)*$//og; # trim
    $lemma_ohne_klammer_aber_mit_zusatz =~ s/\(//og;
    $lemma_ohne_klammer_aber_mit_zusatz =~ s/\)//og;
    
    my $kat_mit_prefix = "Category:".$kat;

    my $klammerzusatz = "";
    if ($lemma_mit_klammerzusatz =~ /\((.+)\)/og) {
      $klammerzusatz = $1;
      # print "KLAMMERZUSATZ:$klammerzusatz:\n";
    }
    
##############

   #   my $url = 'https://commons.wikimedia.org/wiki/Category:Dorfkirche_(Herzsprung_in_der_Uckermark)';
     my $url = 'https://commons.wikimedia.org/wiki/Category:'.URLEncode($kat);
    
#      my $lemma = "";
#     my $lemma_decode = "";
#     if ($url =~ /Category:(.*)$/) {
#        $lemma = $1;
#        $lemma_decode = URLDecode($lemma);
#        $lemma_decode =~ s/_/ /og;
#      }
#       print "LEMMA:$lemma:DECODE:$lemma_decode:\n";
     
       my $check_url = $url.'?action=raw';
       # print "check URL:$check_url:\n"; # exit;

    $agent->get( $check_url );
  my $result2 = $agent->content;
  # print "RESULT:$result2:\n";
  
       if ($result2 =~ /Wikidata infobox/i) {
        # print STDERR "Lemma $check_url hat Wikidata Infobox - do nothing\n";         next;
     } 

  

my $north = "";
my $east = "";
  if ($result2 =~ /Object location/i) {
      # print "Lemma $check_url hat Object location\n";
      if ($result2 =~ /(\s*)\{\{Object location( dec)?(\s*)\|(\s*)([0-9\.]+)(\s*)\|(\s*)([0-9\.]+)(\s*)\}/i) {
       #  print "*** HIER: 1:$1:2.$2:3:$3:4:$4:5:$5:6:$6:7:$7:8:$8\n";
$north = $5;
$east = $8;
     }
        # print "Lemma $check_url hat location $north $east:\n";
   } # Baudenkmal
   
##############

    
    # print "KAT:$kat:LEMMA_MIT:$lemma_mit_klammerzusatz:LEMMA_OHNE:$lemma_ohne_klammerzusatz:\n";

    print "CREATE\n";
   print "LAST\tLde\t\"$lemma_ohne_klammerzusatz\"\n"; # label de - bezeichnung
#    print "LAST\tLde\t\"$lemma_ohne_klammer_aber_mit_zusatz\"\n"; # label de - bezeichnung

   print "LAST\tLmul\t\"$lemma_ohne_klammerzusatz\"\n"; # label mul - bezeichnung

    my $alias = $lemma_mit_klammerzusatz;
    if ($lemma_mit_klammerzusatz ne $lemma_ohne_klammerzusatz) {
      print "LAST\tAde\t\"$alias\"\n"; # alias de - alias
    }
  
#    my $beschreibung = "Kirchengebäude";
    my $beschreibung = "Bauwerk in der Lübecker Altstadt";

    my $beschreibung_en = "building in Lübeck-Altstadt, Germany";


#    if ($klammerzusatz ne "") { $beschreibung = $beschreibung." in ".$klammerzusatz; }
        
    print "LAST\tDde\t\"$beschreibung\"\n"; # description de - beschreibung
	    print "LAST\tDen\t\"$beschreibung_en\"\n"; # description en - beschreibung

    print "LAST\tScommonswiki\t\"$kat_mit_prefix\"\n"; # sitelink
	
 #   print "LAST\tP31\tQ16970\n"; # ist eine: Kirchengebäude
#    print "LAST\tP31\tQ16970\n"; # ist eine: Kirchengebäude
  print "LAST\tP31\tQ811979\n"; # ist eine: Bauwerk
 
    print "LAST\tP17\tQ183\n"; # Staat: Deutschland
 #   print "LAST\tP131\tQ1194\n"; # liegt in der Verwaltungseinheit: Schleswig-Holstein (Q1194)
    print "LAST\tP131\tQ1668684\n"; # liegt in der Verwaltungseinheit: Lübecker Altstadt (Q1668684)
    print "LAST\tP373\t\"$kat\"\n";   # Commonscat-Property
    
#    print "LAST\tP1435\tQ811165\n";   # Schutzkategorie: Baudenkmal 
#    print "LAST\tP1435\tQ85192696\n";   # Schutzkategorie: Baudenkmal 
    print "LAST\tP1435\tQ85192696\n";   # Schutzkategorie (P1435): Kulturdenkmal in Schleswig-Holstein (Q85192696)
    
	

if ($lemma_ohne_klammerzusatz =~ /^Aegidienstraße /) {
    print "LAST\tP669\tQ380606\n";   # Straße: 	Aegidienstraße (Q380606)
}

	
if ($lemma_ohne_klammerzusatz =~ /^Dr.-Julius-Leber-Straße /) {
    print "LAST\tP669\tQ1253777\n";   # Straße: Dr.-Julius-Leber-Straße (Q1253777)
}

if ($lemma_ohne_klammerzusatz =~ /^An der Untertrave /) {
    print "LAST\tP669\tQ482587\n";   # Straße: An der Untertrave (Q482587)
}

if ($lemma_ohne_klammerzusatz =~ /^An der Obertrave /) {
    print "LAST\tP669\tQ482580\n";   # Straße: An der Obertrave (Q482580)
}

if ($lemma_ohne_klammerzusatz =~ /^Dankwartsgrube /) {
    print "LAST\tP669\tQ1164289\n";   # Straße: Dankwartsgrube (Q1164289)
}

if ($lemma_ohne_klammerzusatz =~ /^Engelsgrube /) {
    print "LAST\tP669\tQ1342186\n";   # Straße: Engelsgrube (Q1342186)
}
if ($lemma_ohne_klammerzusatz =~ /^Engelswisch /) {
    print "LAST\tP669\tQ1342212\n";   # Straße: Engelswisch (Q1342212)
}
if ($lemma_ohne_klammerzusatz =~ /^Fleischhauerstraße /) {
    print "LAST\tP669\tQ1427857\n";   # Straße: Fleischhauerstraße (Lübeck) (Q1427857)
}

if ($lemma_ohne_klammerzusatz =~ /^Hundestraße /) {
    print "LAST\tP669\tQ1637530\n";   # Straße: Hundestraße (Q1637530)
}

if ($lemma_ohne_klammerzusatz =~ /^Hüxstraße /) {
    print "LAST\tP669\tQ1652693\n";   # Straße: Hüxstraße (Q1652693)
}

if ($lemma_ohne_klammerzusatz =~ /^Königstraße /) {
    print "LAST\tP669\tQ1689592\n";   # Straße: Königstraße (Q1689592)
}

if ($lemma_ohne_klammerzusatz =~ /^Mengstraße /) {
    print "LAST\tP669\tQ1350892\n";   # Straße: Mengstraße (Q1350892)
}
if ($lemma_ohne_klammerzusatz =~ /^Wahmstraße /) {
    print "LAST\tP669\tQ2806309\n";   # Straße: Wahmstraße (Q2806309)
}

if ($lemma_ohne_klammerzusatz =~ /^Wakenitzmauer /) {
    print "LAST\tP669\tQ2540879\n";   # Straße: Wakenitzmauer (Q2540879)
}







    
#    print "LAST\tP2081\t\"$blfd_id\"\n";   # BLDAM-Objekt-ID 
if (($north ne "") && ($east ne "")) {
  my $cord = '@'.$north.'/'.$east;
    print "LAST\tP625\t$cord\n";   # koordinaten 
 }


 


}
close(IN);
