#!/usr/bin/perl

use strict;

# Crypt::SSLeay muss installiert sein fuer SSL-Support
# apt-get install libwww-mechanize-perl libio-socket-ssl-perl libnet-ssleay-perl
use WWW::Mechanize;
use Data::Dumper;
use HTML::FormatText;
my $USER_AGENT='Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/45.0.2454.101 Safari/537.36';
# See the autocheck parameter, which turns all HTTP errors into fatal errors. When you turn autocheck off, you will need to do all error checking yourself.
my $agent = WWW::Mechanize->new( agent => $USER_AGENT,  autocheck => 0 );

#http://glennf.com/writing/hexadecimal.url.encoding.html
# This pattern takes the hex characters and decodes them back into real characters. The function hex() turns a hex number into decimal; 
# there is no dec() that does the reverse in perl. The "e" at the end of the regexp means "evaluate the replacement pattern as an expression."
sub URLDecode {
    my $theURL = $_[0];
    $theURL =~ tr/+/ /;
    $theURL =~ s/%([a-fA-F0-9]{2,2})/chr(hex($1))/eg;
    $theURL =~ s/<!--(.|\n)*-->//g;
    return $theURL;
}

sub URLEncode {
    my $theURL = $_[0];
    $theURL =~ s/([\W])/"%" . uc(sprintf("%2.2x",ord($1)))/eg;
    return $theURL;
}


####### einträge mit verwaltungseinheit südtirol

# SELECT ?item ?monument WHERE {
#  ?item wdt:P8543 ?monument.
#  ?item wdt:P131 wd:Q15124.
# } order by ?item



####### einträge ohne bild

#SELECT ?item ?monument WHERE {
#  ?item wdt:P8543 ?monument.
#    OPTIONAL {?item wdt:P18 ?bild }  
#  FILTER (!bound(?bild))   # nur jene OHNE bild
#} order by ?item

####### einträge ohne koordinaten

#SELECT ?item ?monument WHERE {
#  ?item wdt:P8543 ?monument.
#    OPTIONAL {?item wdt:P625 ?geo }  
#  FILTER (!bound(?geo))   # nur jene OHNE geographische Koordinaten (P625)
#} order by ?item


my %lookup;
####################
my $INFILE = 'suedtirol-out-umschluesselung.txt';
open ( IN, "< $INFILE") || die("cannot open $INFILE: $! \n");
my $count =0 ;
while(<IN>)
{
    chop;
    my ($LEMMA,$QID) = split("\t",$_);
    # print "LEMMA:$LEMMA:QID:$QID:\n";
    $lookup{$LEMMA} = $QID;
}
close (IN);

$lookup{'Sarntal (Gemeinde)'} = 'Q256173';
$lookup{'Ahrntal (Gemeinde)'} = 'Q402903';
$lookup{'Marling (Suedtirol)'} = 'Q427354';
$lookup{'Andrian (Suedtirol)'} = 'Q373802';
$lookup{'Liste der Baudenkmaeler in Ahrntal (Gemeinde)'} = 'Q1830867';
$lookup{'Liste der Baudenkmaeler in Andrian (Suedtirol)'} = 'Q1830940';

# foreach my $lemma (sort keys %lookup) {
#     print "LEMMA:$lemma:QID:".$lookup{$lemma}.":\n";
# }
# exit;

####################


    

my $INFILE = 'query.csv';

open ( IN, "< $INFILE") || die("cannot open $INFILE: $! \n");

my $count =0 ;
while(<IN>)
{
    chop;
    my ($QID,$MID) = split("\,",$_);
# print "QID:$QID:MID:$MID:\n";


# 15124


# https://heritage.toolforge.org/api/api.php?action=search&format=json&srcountry=it-bz&srlanguage=de&srid=15124
# https://heritage.toolforge.org/api/api.php?action=search&format=xml&srcountry=it-bz&srlanguage=de&srid=15124

################################
my $denkmal_id = $MID;
# print "==============\n";
# my $check_url = 'https://heritage.toolforge.org/api/api.php?format=xml&action=search&srcontinue=it-bz%7Cde%7Cwikipedia%7C'.$denkmal_id.'&srcountry=it-bz&srlang=de';
# my $check_url = 'https://heritage.toolforge.org/api/api.php?format=csv&action=search&srcontinue=it-bz%7Cde%7Cwikipedia%7C'.$denkmal_id.'&srcountry=it-bz&srlang=de';
my $check_url = 'https://heritage.toolforge.org/api/api.php?action=search&format=xml&srcountry=it-bz&srlanguage=de&srid='.$denkmal_id;
#print "CHECK:$check_url:\n";

$agent->get( $check_url );
  my $result2 = $agent->content;
# print "RESULT:$result2:\n";
my @result_arr = split("monument country",$result2);

my $lat = 0;
my $lon = 0;
my $image = "";
my $gemeinde_id = "";
my $list_id = "";
foreach my $line (@result_arr) {
    
    #print "LINE:$line:\n";
      if ($line =~ /id=\"$denkmal_id\"/i) {
#	print "LINE:$line:\n";

   if ($line =~ /lat=\"([0-9.]+)\"/i) {
#	  print "LAT:$1:\n";
	  $lat = $1;
      }
   if ($line =~ /lon=\"([0-9.]+)\"/i) {
#	  print "LAT:$1:\n";
	  $lon = $1;
      }

   if ($line =~ /municipality=\"([^"]+)/i) {
#	print "GEMEINDE:$1:\n";
	my $municipality = $1;
	$municipality =~ s/ü/ue/og;
	$municipality =~ s/ä/ae/og;
	$municipality =~ s/ß/ss/og;
	$municipality =~ s/ö/oe/og;
#	$municipality =~ s/\u00fcd/oe/og;
	if ($municipality =~ /(S.dtirol)/) { $municipality =~ s/$1/Suedtirol/; }
	if ($municipality =~ /(Villn.+)/) { $municipality =~ s/$1/Villnoess/; }
	if ($municipality =~ /(M.+hlbach)/) { $municipality =~ s/$1/Muehlbach/; }
	if ($municipality =~ /(St. Ulrich in Gr.den)/) { $municipality =~ s/$1/St. Ulrich in Groeden/; }
	if ($municipality =~ /(V.ls am Schlern)/) { $municipality =~ s/$1/Voels am Schlern/; }
	if ($municipality =~ /(M.hlwald)/) { $municipality =~ s/$1/Muehlwald/; }
	if ($municipality =~ /(Wolkenstein in Gr.den)/) { $municipality =~ s/$1/Wolkenstein in Groeden/; }
	if ($municipality =~ /(M.lten)/) { $municipality =~ s/$1/Moelten/; }
	if ($municipality =~ /(V.ran)/) { $municipality =~ s/$1/Voeran/; }
	if ($municipality =~ /(Taufers im M.nstertal)/) { $municipality =~ s/$1/Taufers im Muenstertal/; }
	if ($municipality =~ /(L.sen)/) { $municipality =~ s/$1/Luesen/; }
	if ($municipality =~ /(St. Christina in Gr.den)/) { $municipality =~ s/$1/St. Christina in Groeden/; }



	
#	print "municipality:$municipality:\n";

         $gemeinde_id = $lookup{$municipality};
#print "GID:$gemeinde_id:\n";
        my $list_lemma =  'Liste der Baudenkmaeler in '.$municipality;
        $list_id = $lookup{$list_lemma};
        if ($gemeinde_id eq "") {
          print "**** WARNING: keine QID für Gemeinde:$municipality:gefunden\n";
        }
        if ($list_id eq "") {
          print "**** WARNING: keine QID für:$list_lemma:gefunden\n";
        }
   }
}
}
################################


    if ($gemeinde_id ne "") {
     print "-$QID\tP131\tQ15124\n";   # Südtirol (Q15124) entfernen
     print "$QID\tP131\t$gemeinde_id\n";   
     if ($list_id ne "") {
       print "$QID\tP2817\t$list_id\n";
     }
     print "$QID\tP973\t\"".$check_url."\"\tP407\tQ188\n"; # wird beschrieben in URL (P973) - Sprache: Deutsch
      
#          print "LAST\tP1435\tQ18946666\tS248\tQ97569340\n";   # : Schutzkategorie (P1435): Baudenkmal in Südtirol (Q18946666)
#   Fundstelle   nachgewiesen in: Monumentbrowser - S248:Q97569340
     
#     wird beschrieben in URL (P973)

# ist in der Kulturdenkmal-Liste (P2817): Liste der denkmalgeschützten Objekte in ....
     
     
     }
    
    
    if (($lat ne "") && ($lon ne "")) {
      my $cord = '@'.$lat.'/'.$lon;
 #    print "$QID\tP625\t$cord\n";   # koordinaten 
    }

     # erstellt: Bild (P18): Heiligkreuz in Kematen, Klobenstein, Ritten.jpg
    if ($image ne "") {
     
  #   print "$QID\tP18\t\"$image\"\n";   # bild
     
     }
    
# exit;


}
close(IN);

exit;


